[project]
name = "yakatak-api"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic-settings>=2.10.1",
]

[dependency-groups]
dev = [
    "fastapi-cli>=0.0.10",
]

[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff.lint]
extend-select = ["I"]
